# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc5c5dd5d639a0703ce5f8c9ad132ecb8b7aeb9b1a61b0355c06e7d053cddebe5f54bafd791ac38a0ace56fcd8181716c3168eda872db2d77a6e34a55cea7492

test:
  secret_key_base: e39eae2f88ad505c660baeb70e70223e5f4fddd30f1a478ab59ef009b34a26354493d853e88e9fb8c77c31cbbee6f19eb1c490a8534a4e7067cd38a07ad08c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
